config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end
  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def update
    p = Person.find(params[:id])
    p.update(person_params)
    redirect_to '/people'
  end

  def destroy
    p = Person.find(params[:id])
    p.destroy
    redirect_to '/people'
  end
  private

  def person_params
    params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav.html.erb
<%= link_to "Profiles", people_path %>
<%= link_to "New Profile", new_person_path %>

app/views/layouts/application.html.erb
<title>People</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div style="background: grey;">
    <%= yield %>
  </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<p></p>
<%= f.label :hair_color %>
<%= f.text_field :hair_color %>
<p></p>
<%= f.label :age %>
<%= f.text_field :age %>
<p></p>
<%= f.label :eye_color %>
<%= f.text_field :eye_color %>
<p></p>
<%= f.label :gender %>
<%= f.text_field :gender %>
<p></p>
<%= f.label :alive %>
<%= f.check_box :alive %>
<p></p>
<%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h1>Edit <%= @person.name %>'s information</h1>
<%= render 'form' %>

app/views/people/index.html.erb
<h1>List of Registered Persons</h1>

<% @people.each do |p| %>
<p></p>
PERSON <%= p.name %>
<%= link_to 'information', person_path(p) %>
<%= link_to 'edit', edit_person_path(p)%>
<%= link_to 'delete', p, :method => :delete %>
<p></p>

<% end %>

app/views/people/new.html.erb
<h1>Add New PERSON</h1>
<%= render 'form' %>

app/views/people/show.html.erb
<% if @person.alive == true %>
<h1>Welcome <%= @person.name %></h1>
<% else %>
<h1>Here lie <%= @person.name %> RIP</h1>
<% end %>
<p>Age: <%= @person.age %></p>
<p>Hair Color: <%= @person.hair_color %></p>
<p>Eye Color: <%= @person.eye_color %></p>
<p>Gender: <%= @person.gender %></p>

<%= link_to "Back", people_path %>

app/views/static_pages/home.html.erb
Check if people are dead or alive